name: Deploy for ci/cd

# 트리거
on:
  # 원인 : 푸시
  push:
    # 대상 브런치
    branches:
      # 대상 브런치는 main(본인 브런치명)
      - master

# 해야될 일 => jobs
jobs:
  # 잡 전체에 대한 이름 (커스텀)
  cicd-deploy:
    # ubuntu linux 준비 -> 해당 작업이 진행되는 베이스 OS 지정
    runs-on: ubuntu-latest
    # 개별 작업 단계 지정
    steps:
      # https://github.com/actions/checkout 사용
      # 해당 작업이 수행되면 본 레포지토리(저장소)가 체크아웃되어 os단에 저장
      # 향후 워클로우에서 엑세스 처리 가능하게 구성된다
      # name: 작업명 기술, uses: 실제할일 기술
      - name: Github Repository 내 파일들 checkout(불러오기) 수행
        uses: actions/checkout@v4

      # JDK 17 버전 설치
      # https://github.com/actions/setup-java
      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # application.yml 동적 생성 제발되라라
      # 소스 코드내에 위치 (덮어쓰기?, 신규작성?)
      # RDS 세팅된 이후 진행ㄴㄴㄴㄴㅇㅁㄴㅇㅇ
      # 현재는 skip
      #수정완료
      - name: application.yml 동적 생성
        run: |
         mkdir -p ./src/main/resources/
         echo "${{ secrets.PRODUCTS_APPLICATION_YML }}" > ./src/main/resources/application.yml
         ls ./src/main/resources/

      # build 준비
      # chmod +x ./gradlew : 퍼미션 오류 발생시 처리
      # ./gradlew clean build
      - name: 단위 테스트 및 빌드
        # 명령어가 여러개면 | 추가
        # 1. 빌드용 쉘스크립트(gradlew)를 퍼미션 조정
        # 2. 빌드
        # 3. 현재 위치 확인
        #    /home/runner/work/demo-deploy/demo-deploy
        # 4. 현재 위치 목록
        #    build ... src
        # 5. 빌드된 산출물의 목록 확인
        #    demo-deploy-0.0.1-SNAPSHOT-plain.jar ...
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 이름이 너무 길므로 적당하게 수정 -> 리눅스 명령어
      # 파일 위치를 변경하면서 이름도 변경 -> mv
      - name: 관리상 빌드된 결과물의 이름을 변경 처리
        run: |
          mv ./build/libs/*SNAPSHOT.jar ./run.jar
          ls

      # EC2 로 업로드
      # https://github.com/appleboy/scp-action
      # SSH를 통해서 파일등을 복사(업로드)
      # 호스트정보(IP), 접속자명(ubuntu), 키파일(pem) -> 시크릿!!
      # 업로드 대상(run.jar)
      # 타겟(EC2)의 특정 경로(복사될 위치), /home/ubuntu/server/demo
      - name: EC2에 jar파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: run.jar
          target: /home/ubuntu/server/demo


          #추가 완료 수정정
      - name: Run jar in EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/web
            mkdir /home/ubuntu/server/web
            mv /home/ubuntu/server/demo/run.jar /home/ubuntu/server/web/run.jar
            cd /home/ubuntu/server/web
            sudo fuser -k -n tcp 8060 || true
            nohup java -jar run.jar> ./output.log 2>&1 &
            rm -rf /home/ubuntu/server/demo

